#!/usr/bin/env python3
"""Generate XSHELLS heteroflux boundary files with verified normalization.

File format (from problems/heteroflux/cmb_heat_flux_Y22.txt):
  %XS Temperature flux lmax=2 mmax=2 norm=1
  % comments; then one "re im  #l=..,m=.." line per (l,m), grouped by m
  starting at m=0 (m=0 implies zero imaginary part).
Paper §F1 requires <H>S = 0 and <H^2>S = 1 for matched-pattern comparisons.
Stock-file convention (problems/heteroflux/cmb_heat_flux_Y22.txt, header
norm=1): a single real mode carries amplitude 1/sqrt(2), i.e. mode power 1/2.
Multi-mode maps below keep the same total power (Y10+Y30 at 1/2 each), so
patterns are power-matched; the physical amplitude is set by the dq multiplier
in the par file. PHYSICAL-SPACE MEASUREMENT (tools/verify_fluxmaps.py,
2026-09-16): zero mean confirmed for all three maps; parity Y21=-1.000
(anti-symmetric), Y22=+1.000 (symmetric), Y10+Y30=-1.000; measured spatial
RMS ≈ 0.1995 per map — NOT unit RMS. The <H^2>S = 1 normalization of paper
§F1 is therefore NOT yet established; the dq/q* conversion (AUDIT item) must
absorb the measured RMS. Do not claim unit RMS for these files.
"""
import math
import os

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                   "..", "xshells")
SQ = math.sqrt(2.0)


def write_flux(path, lmax, mmax, modes):
    """modes: dict {(l,m): (re,im)}. Verifies stock power convention (total
    mode power 1/2) and zero mean (no l=0,m=0) before writing."""
    power = sum(re * re + im * im for re, im in modes.values())
    assert abs(power - 0.5) < 1e-9, f"pattern power must be 1/2: {power}"
    assert (0, 0) not in modes, "l=0,m=0 forbidden (no stationary solution)"
    with open(path, "w") as f:
        f.write(f"%XS Temperature flux lmax={lmax} mmax={mmax} norm=1\n")
        f.write("% generated by tools/make_fluxmaps.py; coefficient power 1/2\n")
        f.write("% (NOT unit spatial RMS: measured rms ~= 0.1995, see\n")
        f.write("% tools/verify_fluxmaps.py report; dq absorbs the scale)\n")
        for m in range(0, mmax + 1):
            for l in range(m, lmax + 1):
                re, im = modes.get((l, m), (0.0, 0.0))
                tag = "" if (l, m) in modes else " (zero)"
                f.write(f"{re:.16f} {im:.16f}  #l={l},m={m}{tag}\n")
    return power


if __name__ == "__main__":
    wdir = os.path.join(OUT, "protocol_W")
    pdir = os.path.join(OUT, "protocol_P")
    os.makedirs(wdir, exist_ok=True)
    os.makedirs(pdir, exist_ok=True)
    # W: anti-symmetric Y21 (reversing) and symmetric Y22 (control).
    n = write_flux(os.path.join(wdir, "cmb_Y21.txt"), 2, 2,
                   {(2, 1): (-1.0 / SQ, 0.0)})
    print(f"cmb_Y21.txt power={n:.12f}")
    n = write_flux(os.path.join(wdir, "cmb_Y22.txt"), 2, 2,
                   {(2, 2): (-1.0 / SQ, 0.0)})
    print(f"cmb_Y22.txt power={n:.12f}")
    # P: Y10+Y30 equal-power pair (half-range convention noted
    # in par file; amplitude set by dq there).
    n = write_flux(os.path.join(pdir, "cmb_Y10_Y30.txt"), 3, 0,
                   {(1, 0): (0.5, 0.0), (3, 0): (0.5, 0.0)})
    print(f"cmb_Y10_Y30.txt power={n:.12f}")
    print("flux maps OK")
